import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All Devices', icon: 'Smartphone' },
  { id: 'apple', name: 'Apple', icon: 'Apple' },
  { id: 'samsung', name: 'Samsung', icon: 'Smartphone' },
  { id: 'google', name: 'Google', icon: 'G' },
  { id: 'xiaomi', name: 'Xiaomi', icon: 'Smartphone' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Titanium Lumina Pro 16',
    brand: 'Apple',
    price: 1199,
    image: 'https://picsum.photos/seed/iphone16/800/800',
    category: 'apple',
    description: 'The ultimate smartphone experience with the new A18 Pro chip and a stunning titanium design.',
    specs: {
      display: '6.7-inch Super Retina XDR',
      processor: 'A18 Pro chip',
      ram: '8GB',
      storage: '256GB, 512GB, 1TB',
      camera: '48MP Main | 12MP Ultra Wide | 12MP Telephoto',
      battery: 'Up to 29 hours video playback',
    },
    colors: ['#3C3D3A', '#F2F2F2', '#E3D0B9'],
    storageOptions: ['256GB', '512GB', '1TB'],
    isNew: true,
  },
  {
    id: '2',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 1299,
    image: 'https://picsum.photos/seed/s24ultra/800/800',
    category: 'samsung',
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra, you can unleash whole new levels of creativity.',
    specs: {
      display: '6.8-inch Dynamic AMOLED 2X',
      processor: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      storage: '256GB, 512GB, 1TB',
      camera: '200MP Main | 50MP Periscope | 10MP Telephoto | 12MP Ultra Wide',
      battery: '5,000 mAh',
    },
    colors: ['#2C2C2C', '#E0E0E0', '#B0C4DE'],
    storageOptions: ['256GB', '512GB', '1TB'],
    isNew: true,
  },
  {
    id: '3',
    name: 'Pixel 9 Pro',
    brand: 'Google',
    price: 999,
    image: 'https://picsum.photos/seed/pixel9pro/800/800',
    category: 'google',
    description: 'The most powerful Pixel yet, with a pro-level camera and Google AI.',
    specs: {
      display: '6.3-inch Super Actua Display',
      processor: 'Google Tensor G4',
      ram: '16GB',
      storage: '128GB, 256GB, 512GB',
      camera: '50MP Main | 48MP Ultra Wide | 48MP Telephoto',
      battery: '4,700 mAh',
    },
    colors: ['#1A1A1A', '#F5F5F5', '#E0E0E0'],
    storageOptions: ['128GB', '256GB', '512GB'],
    isNew: true,
  },
  {
    id: '4',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price: 1099,
    image: 'https://picsum.photos/seed/xiaomi14ultra/800/800',
    category: 'xiaomi',
    description: 'A masterpiece of mobile photography, co-engineered with Leica.',
    specs: {
      display: '6.73-inch AMOLED',
      processor: 'Snapdragon 8 Gen 3',
      ram: '16GB',
      storage: '512GB',
      camera: '50MP Quad Camera System',
      battery: '5,000 mAh',
    },
    colors: ['#000000', '#FFFFFF'],
    storageOptions: ['512GB'],
  },
];
